### ISSUE TITLE
add new command "gitflow update-translation"

### ISSUE THREAD

**Issue by z3niths** [crazyfactory/gitflow#26]
This command will
- Copy all translation from master branch into current branch with confirmation
- git command = "git checkout master -- dirname"
- dir = language folder

Please check all cases
- We have a change in the folder
- We don't have a change in the folder

**Comment by adhocore** [comment]
it looks like very domain specific feature (for now only valid for `shop`)
do you think we should have such feature?

**Comment by z3niths** [comment]
hmm true ... but we never have a toll that will working with git command.
It cants even be a shop feature. Implement it here should be alright IMO.

Or we can change the command to shop-update-translation ?

**Comment by adhocore** [comment]
ok lets have it here but slightly modified:
```sh
gitflow sync-from <branch> <dirname>
# gitflow sync-from master language
```

now we can also support aliasing some reusable commands:
```sh
# set alias
gitflow set alias trans "gitflow sync-from master language"

# usage
gitflow trans
```

**Comment by adhocore** [comment]
> We have a change in the folder

if there is local change in folder then we can perhaps rebase (first need to check if possible)

**Comment by adhocore** [comment]
# recommended alias
```
gitflow alias trans "git checkout master -- language && git commit"
```

**Comment by CGundl** [comment]
technical. no need to test this. and released already. please dont keep tickets like this in QA WIP

**Comment by CGundl** [comment]
i cant move it out from QA WIP :( ?

**Comment by adhocore** [comment]
ooh i dont know how it got to QA panel, maybe that is automatic trigger on merge or something?

**Comment by konthornR** [comment]
![image](https://user-images.githubusercontent.com/10362733/70692232-75f46800-1ced-11ea-84a0-9a8a6c391222.png)
![image](https://user-images.githubusercontent.com/10362733/70692237-78ef5880-1ced-11ea-8888-46e1a31df8f5.png)
@adhocore am wondering how to use this cmd? I want to pull translation from master into my working branch

**Comment by adhocore** [comment]
in shop project: `gitflow uptrans`
